[package]
name = "sel4_task"
version = "0.1.0"
edition = "2021"

[dependencies]
sel4_common = { path = "../sel4_common" }
sel4_cspace = { path = "../sel4_cspace" }
sel4_vspace = { path = "../sel4_vspace" }
log = "0.4.21"

[features]
ENABLE_SMP = []